export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REFRESH_USER_SUCCESS = 'REFRESH_USER_SUCCESS';
export const CONFIRM_USER_DETAILS = 'CONFIRM_USER_DETAILS';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';